### ISSUE TITLE
Send PR to stylelint docs?

### ISSUE THREAD

**Issue by jeddy3** [primer/stylelint-selector-no-utility#1]
This plugin looks great!

Would you consider sending a PR to `stylelint` adding it to [the list of plugins](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md)? Or, let me know if you're OK with it being added, and I can do it for you. The list is looking a little sparse at the moment you see, and we're keen to adding some good quality plugins to it to get things going :)

**Comment by jonrohan** [comment]
I considered it, but currently the [plugin is super specific](https://github.com/primer/stylelint-selector-no-utility/blob/master/README.md#selector-no-utility) to [primer-utilities](https://github.com/primer/utilities)

I think a little bit of work would need to be done to allow the passing in of someone's own utility file or array of classes.

**Comment by jeddy3** [comment]
I think it's dandy that the plugin is currently specific to primer. I was thinking of a putting it into a new section within the list: Toolkits -> Primer. As a way of an explanation, we're keen to highlight _well written_ plugins at the moment as there's only a handful out there and there's not much reference material for people wanting to start writing their own plugins.

If someone thinks this plugin would be useful for their toolkit too and adapts it to be more generic, then we can simple shift things around in the list. But at the moment I think it's great as this plugin highlights that plugins can be specific to a toolkit - it's even one of the use cases of plugins we list within the docs :)

I hope that better explains what I was originally thinking. Let me know what you think. I'm happy either way as it's just nice to see the plugin system being used :)

**Comment by jonrohan** [comment]
Ok, cool, if you think it would be helpful in that context, i'm 👍

**Comment by jeddy3** [comment]
Thanks!. I've got a few documentation amends to do next week, and so I can update the list of plugins when I do that.
